### ISSUE TITLE
Wrong Token URL

### ISSUE THREAD

**Issue by opendevl** [RallySoftware/rally-oauth-examples#3]
Hi,
Both the Authentication and Token are "https://rally1.rallydev.com/login/oauth2/auth" but the Token URL doesn't work.
I think the Token URL is "https://rally1.rallydev.com/login/oauth2/token".
So, c-an you please change the token url in the README.md file?

**Comment by grammati** [comment]
Fixed, thanks for the report. Let us know if you see any other inaccuracies.
